import wci.intermediate.RoutineCode;

public enum DefaultRoutineCode implements RoutineCode{
	ADDTOLIST, CREATENEWLIST, LISTSIZE, GETFROMLIST, SETTOLIST,
	
	ADDCOLOR, CREATEPAINTGUI, ISLEFTCLICK, ISRIGHTCLICK, ISDRAG, GETMOUSEX, GETMOUSEY,
	CREATELINE, ADDPOINT, ENDLINE, PAINTGUIEXITED, GETCOLORSIZE, REFRESH,
	
	SQRTI, SQRTR, TOREAL, TOINT, RANDOM
}
